# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

from ast import If
from operator import ne


limit = 4000000


def fib(oneNumber, twoNumber):
    return oneNumber + twoNumber


fibbonacciEvenNumbers = []
oneNumber = 0
twoNumber = 1

while twoNumber < limit:
    newNumber = fib(oneNumber, twoNumber)

    if newNumber % 2 == 0:
        # even
        fibbonacciEvenNumbers.append(newNumber)

    oneNumber = twoNumber
    twoNumber = newNumber


total = sum(fibbonacciEvenNumbers)

print(total)